spring:
  application:
    name: clothingstore

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:clothingstore}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:phuquy2k3.2003@gmail.com}
    password: ${MAIL_PASSWORD:kwocncbgjrsstlia}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      example:
        clothingstore: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

jwt:
  base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 2592000

api:
  version: api/v1
