spring:
  application:
    name: clothingstore

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 15MB

  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com:
      example:
        clothingstore: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: list
    default-models-expand-depth: 0
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  model-and-view-allowed: false
  show-actuator: false
  show-login-endpoint: false
  use-management-port: false
  paths-to-match: /**

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  base64-secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY}

api:
  version: ${API_VERSION}

google:
  cloud:
    credentials:
      path: ${GOOGLE_CLOUD_CREDENTIALS_PATH}
    storage:
      project-id: ${GOOGLE_CLOUD_PROJECT_ID}
      bucket: ${GOOGLE_CLOUD_BUCKET}

vnpay:
  tmncode: ${VNPAY_TMNCODE}
  hashsecret: ${VNPAY_HASHSECRET}
  url: ${VNPAY_URL}
  returnurl: ${VNPAY_RETURNURL}
