spring:
  application:
    name: clothingstore

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: ${DEFER_DATASOURCE_INITIALIZATION}

  sql:
    init:
      mode: ${SQL_INIT_MODE}
      encoding: UTF-8

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      enabled: true
      max-file-size: 3MB
      max-request-size: 15MB

  data:
    # web:
    #   pageable:
    #     one-indexed-parameters: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jackson:
    time-zone: Asia/Ho_Chi_Minh

logging:
  level:
    com:
      example:
        clothingstore: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    relaxed-query-chars: "|,(,),{,},[,],^"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: list
    default-models-expand-depth: 0
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  model-and-view-allowed: false
  show-actuator: false
  show-login-endpoint: false
  use-management-port: false
  paths-to-match: /**

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  base64-secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY}

api:
  version: ${API_VERSION}

google:
  cloud:
    credentials:
      path: ${GOOGLE_CLOUD_CREDENTIALS_PATH}
    storage:
      project-id: ${GOOGLE_CLOUD_PROJECT_ID}
      bucket: ${GOOGLE_CLOUD_BUCKET}
  auth:
    client-id: ${GOOGLE_AUTH_CLIENT_ID}
    client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_AUTH_REDIRECT_URI}
    base-url: https://oauth2.googleapis.com
  userinfo:
    base-url: https://www.googleapis.com/oauth2/v1/userinfo

vnpay:
  tmncode: ${VNPAY_TMNCODE}
  hashsecret: ${VNPAY_HASHSECRET}
  url: ${VNPAY_URL}
  returnurl: ${VNPAY_RETURNURL}

ghn:
  api:
    url: ${GHN_API_URL}
    token: ${GHN_API_TOKEN}
  shop:
    id: ${GHN_SHOP_ID}
    district: ${GHN_SHOP_DISTRICT_ID}
    weight: ${GHN_SHOP_WEIGHT}
    length: ${GHN_SHOP_LENGTH}
    width: ${GHN_SHOP_WIDTH}
    height: ${GHN_SHOP_HEIGHT}
    free-shipping-threshold: ${GHN_SHOP_FREE_SHIPPING_THRESHOLD}

goong:
  api:
    base-url: ${GOONG_API_BASE_URL}
    key: ${GOONG_API_KEY}
    vehicle-type: ${GOONG_API_VEHICLE_TYPE}
