spring:
  application:
    name: clothingstore

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  datasource:
    url: jdbc:mysql://localhost:3306/clothingstore
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    web:
      pageable:
        one-indexed-parameters: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: phuquy2k3.2003@gmail.com
    password: kwocncbgjrsstlia
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  base64-secret: qoAEABDke07+AVLepXB4aCMtsT0wMAqR5x2VFyldsnx6e75YQkJH2UcZKTjEyoNgG71SBCXfq5N6NVZxWOfsHQ==
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 2592000

api:
  version: api/v1

logging:
  level:
    com:
      example:
        clothingstore: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
