# Development Environment Configuration

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${DEV_MYSQL_HOST}:${DEV_MYSQL_PORT}/${DEV_MYSQL_DATABASE}
    username: ${DEV_MYSQL_USER}
    password: ${DEV_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  # Data Initialization
  sql:
    init:
      mode: ${DEV_SQL_INIT_MODE}

# Logging Configuration
logging:
  level:
    com:
      example:
        clothingstore: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

# Server Configuration
server:
  port: ${DEV_SERVER_PORT}

# API Documentation
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    disable-swagger-default-url: true
    doc-expansion: list
    default-models-expand-depth: 0
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  model-and-view-allowed: false
  show-actuator: false
  show-login-endpoint: false
  use-management-port: false
  paths-to-match: /**

# CORS Configuration
cors:
  allowed-origins: ${DEV_CORS_ALLOWED_ORIGINS}

# Application Domain
domain: ${DEV_DOMAIN} 