# Production Environment Configuration

# Database Configuration
spring:
  datasource:
    url: jdbc:mysql://${PROD_MYSQL_HOST}:${PROD_MYSQL_PORT}/${PROD_MYSQL_DATABASE}
    username: ${PROD_MYSQL_USER}
    password: ${PROD_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  
  # Data Initialization
  sql:
    init:
      mode: ${PROD_SQL_INIT_MODE}

# Logging Configuration
logging:
  level:
    com:
      example:
        clothingstore: INFO
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

# Server Configuration
server:
  port: ${PROD_SERVER_PORT}

# API Documentation
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

# CORS Configuration
cors:
  allowed-origins: ${PROD_CORS_ALLOWED_ORIGINS}

# Application Domain
domain: ${PROD_DOMAIN} 