# Application Configuration
spring:
  application:
    name: clothingstore
  # Set default profile to dev
  profiles:
    default: dev

  # Database Configuration
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: ${DEFER_DATASOURCE_INITIALIZATION}
    properties:
      hibernate:
        format_sql: false

  # Data Initialization
  sql:
    init:
      encoding: UTF-8

  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

  # Time Zone Configuration
  jackson:
    time-zone: Asia/Ho_Chi_Minh

# Server Configuration
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    relaxed-query-chars: "|,(,),{,},[,],^"

# Security Configuration
jwt:
  base64-secret: ${JWT_SECRET}
  access-token-validity-in-seconds: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity-in-seconds: ${JWT_REFRESH_TOKEN_VALIDITY}

# API Version
api:
  version: ${API_VERSION}

# External Services Configuration
google:
  cloud:
    credentials:
      path: ${GOOGLE_CLOUD_CREDENTIALS_PATH}
    storage:
      project-id: ${GOOGLE_CLOUD_PROJECT_ID}
      bucket: ${GOOGLE_CLOUD_BUCKET}
  auth:
    client-id: ${GOOGLE_AUTH_CLIENT_ID}
    client-secret: ${GOOGLE_AUTH_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_AUTH_REDIRECT_URI}
    base-url: https://oauth2.googleapis.com
  userinfo:
    base-url: https://www.googleapis.com/oauth2/v1/userinfo

vnpay:
  tmncode: ${VNPAY_TMNCODE}
  hashsecret: ${VNPAY_HASHSECRET}
  url: ${VNPAY_URL}
  returnurl: ${VNPAY_RETURNURL}

ghn:
  api:
    url: ${GHN_API_URL}
    token: ${GHN_API_TOKEN}
  shop:
    id: ${GHN_SHOP_ID}
    district: ${GHN_SHOP_DISTRICT_ID}
    weight: ${GHN_SHOP_WEIGHT}
    length: ${GHN_SHOP_LENGTH}
    width: ${GHN_SHOP_WIDTH}
    height: ${GHN_SHOP_HEIGHT}
    free-shipping-threshold: ${GHN_SHOP_FREE_SHIPPING_THRESHOLD}

goong:
  api:
    base-url: ${GOONG_API_BASE_URL}
    key: ${GOONG_API_KEY}
    vehicle-type: ${GOONG_API_VEHICLE_TYPE}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL}

openai:
  api-key: ${OPENAI_API_KEY}

pinecone:
  api-key: ${PINECONE_API_KEY}
  environment: ${PINECONE_ENVIRONMENT}
  index: ${PINECONE_INDEX_NAME}
  namespace: ${PINECONE_NAMESPACE}